-- Initial test data: exactly the 10 requested boxers.
-- Values were manually checked against the source URLs on 2026-08-20.
-- Unknown or conflicting values are intentionally NULL.

insert into public.boxers (
  slug, name_ja, name_kana, name_en, ring_name, boxrec_id, boxrec_url,
  nationality, birth_date, birthplace, career_status, gym, weight_class, stance,
  height_cm, reach_cm, pro_debut_date,
  total_fights, wins, losses, draws, no_contests, ko_wins,
  world_champion_experience, current_titles, past_major_titles, world_title_weight_classes,
  ranking_wba, ranking_wbc, ranking_ibf, ranking_wbo,
  next_fight_date, next_opponent, next_venue, next_event_name,
  source_name, source_url, source_checked_at, field_sources, is_published
)
values
(
  'naoya-inoue', '井上尚弥', 'いのうえ なおや', 'Naoya Inoue', 'Monster', '628407', 'https://boxrec.com/en/box-pro/628407',
  '日本', '1993-04-10', '神奈川県座間市', 'active', '大橋ボクシングジム', 'スーパーバンタム級', 'オーソドックス',
  165, 171, '2012-10-02',
  33, 33, 0, 0, 0, 27,
  true, 'WBA・WBC・IBF・WBO世界スーパーバンタム級', 'WBC世界ライトフライ級、WBO世界スーパーフライ級、WBA・IBF・WBC・WBO世界バンタム級', 'ライトフライ級、スーパーフライ級、バンタム級、スーパーバンタム級',
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL,
  '井上尚弥オフィシャルWEBサイト', 'https://naoya-inoue.com/profile/', '2026-08-20T00:00:00+09:00',
  '{"profile":{"name":"井上尚弥オフィシャルWEBサイト","url":"https://naoya-inoue.com/profile/"},"record":{"name":"井上尚弥オフィシャルWEBサイト","url":"https://naoya-inoue.com/profile/"},"stance":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/en/box-pro/628407"},"reach_cm":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/en/box-pro/628407"},"pro_debut_date":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/en/box-pro/628407"}}'::jsonb, true
),
(
  'junto-nakatani', '中谷潤人', 'なかたに じゅんと', 'Junto Nakatani', '愛の拳士', '718508', 'https://boxrec.com/en/box-pro/718508',
  '日本', '1998-01-02', '三重県員弁郡東員町', 'active', 'M.Tボクシングジム', 'スーパーバンタム級', 'サウスポー',
  173, 174, '2015-04-26',
  33, 32, 1, 0, 0, 24,
  true, 'なし', 'WBO世界フライ級、WBO世界スーパーフライ級、WBC・IBF世界バンタム級', 'フライ級、スーパーフライ級、バンタム級',
  5, 1, NULL, 2,
  NULL, NULL, NULL, NULL,
  '中谷潤人公式プロフィール', 'https://junto.jp/profile', '2026-08-20T00:00:00+09:00',
  '{"profile":{"name":"中谷潤人公式プロフィール","url":"https://junto.jp/profile"},"record":{"name":"中谷潤人公式プロフィール","url":"https://junto.jp/profile"},"birthplace":{"name":"三菱重工相模原ダイナボアーズ公式発表","url":"https://league-one.jp/news/3216"}}'::jsonb, true
),
(
  'kenshiro-teraji', '寺地拳四朗', 'てらじ けんしろう', 'Kenshiro Teraji', NULL, '692967', 'https://boxrec.com/en/box-pro/692967',
  '日本', '1992-01-06', '京都府城陽市', 'active', 'BMBボクシングジム', 'スーパーフライ級', 'オーソドックス',
  165, 164, '2014-08-03',
  28, 26, 2, 0, 0, 16,
  true, 'WBO世界スーパーフライ級', 'WBCユース・ライトフライ級、日本ライトフライ級、OPBF東洋太平洋ライトフライ級、WBC世界ライトフライ級、WBA世界ライトフライ級、WBC世界フライ級、WBA世界フライ級', 'ライトフライ級、フライ級、スーパーフライ級',
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL,
  'BMBボクシングジム公式プロフィール', 'https://bmbsportsgym.com/champ/', '2026-08-20T00:00:00+09:00',
  '{"profile":{"name":"BMBボクシングジム公式プロフィール","url":"https://bmbsportsgym.com/champ/"},"record":{"name":"BMBボクシングジム公式プロフィール","url":"https://bmbsportsgym.com/champ/"},"height_cm":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/wiki/index.php/Kenshiro_Teraji"},"reach_cm":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/wiki/index.php/Kenshiro_Teraji"}}'::jsonb, true
),
(
  'tenshin-nasukawa', '那須川天心', 'なすかわ てんしん', 'Tenshin Nasukawa', NULL, '853210', 'https://boxrec.com/en/box-pro/853210',
  '日本', '1998-08-18', '千葉県松戸市', 'active', '帝拳ボクシングジム', 'バンタム級', 'サウスポー',
  165, 176, '2023-04-08',
  9, 8, 1, 0, 0, 3,
  false, 'なし', 'WBOアジアパシフィック・バンタム級', 'なし',
  NULL, 1, NULL, 1,
  '2026-09-27', '井上拓真', 'トヨタアリーナ東京', 'Prime Video Boxing 16',
  '帝拳公式プロフィール', 'https://www.teiken.com/profile/tenshin.html', '2026-08-20T00:00:00+09:00',
  '{"profile":{"name":"帝拳公式プロフィール","url":"https://www.teiken.com/profile/tenshin.html"},"record":{"name":"帝拳公式プロフィール","url":"https://www.teiken.com/profile/tenshin.html"},"reach_cm":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/wiki/index.php/Tenshin_Nasukawa"},"next_fight_date":{"name":"Amazon公式発表","url":"https://www.aboutamazon.jp/news/entertainment/prime-boxing-16"}}'::jsonb, true
),
(
  'seiya-tsutsumi', '堤聖也', 'つつみ せいや', 'Seiya Tsutsumi', NULL, '829718', 'https://boxrec.com/en/box-pro/829718',
  '日本', '1995-12-24', '熊本県', 'active', '角海老宝石ジム', 'バンタム級', 'スイッチ',
  166, 164, '2018-03-27',
  16, 13, 0, 3, 0, 8,
  true, 'WBA世界バンタム級休養王者', '日本バンタム級', 'バンタム級',
  1, 27, NULL, NULL,
  NULL, NULL, NULL, NULL,
  'BoxRec（手動確認） / wiAth公式プロフィール', 'https://boxrec.com/en/box-pro/829718', '2026-08-20T00:00:00+09:00',
  '{"profile":{"name":"wiAth公式プロフィール","url":"https://www.wiath.co.jp/client_profile/tsutsumi.html"},"record":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/en/box-pro/829718"},"gym":{"name":"wiAth公式プロフィール","url":"https://www.wiath.co.jp/client_profile/tsutsumi.html"},"next_fight_date":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/en/box-pro/829718"}}'::jsonb, true
),
(
  'tomoya-tsuboi', '坪井智也', 'つぼい ともや', 'Tomoya Tsuboi', NULL, '868148', 'https://boxrec.com/en/box-pro/868148',
  '日本', '1996-03-25', '静岡県浜松市', 'active', '帝拳ジム', 'スーパーフライ級', NULL,
  160, 162, '2025-03-13',
  4, 3, 0, 0, 1, 2,
  false, 'WBOアジアパシフィック・バンタム級', 'なし', 'なし',
  3, 1, NULL, 1,
  '2026-09-27', 'リカルド・マラジカ', 'トヨタアリーナ東京', 'Prime Video Boxing 16',
  '帝拳公式プロフィール / Boxing News', 'https://www.teiken.com/profile/tsuboi.html', '2026-08-20T00:00:00+09:00',
  '{"profile":{"name":"帝拳公式プロフィール","url":"https://www.teiken.com/profile/tsuboi.html"},"record":{"name":"Boxing News","url":"https://boxingnews.jp/en/english-fight-result/115619/"},"next_fight_date":{"name":"Amazon公式発表","url":"https://www.aboutamazon.jp/news/entertainment/prime-boxing-16"}}'::jsonb, true
),
(
  'yoshiki-takei', '武居由樹', 'たけい よしき', 'Yoshiki Takei', NULL, '990774', 'https://boxrec.com/en/box-pro/990774',
  '日本', '1996-07-12', '東京都足立区', 'active', '大橋ボクシングジム', 'スーパーバンタム級', 'サウスポー',
  170, 171, '2021-03-11',
  13, 12, 1, 0, 0, 9,
  true, 'なし', 'WBO世界バンタム級、OPBF東洋太平洋スーパーバンタム級', 'スーパーバンタム級、バンタム級',
  6, 23, NULL, 2,
  NULL, NULL, NULL, NULL,
  '武居由樹オフィシャルサイト / BoxRec（手動確認）', 'https://yoshikitakei.com/', '2026-08-20T00:00:00+09:00',
  '{"profile":{"name":"武居由樹オフィシャルサイト","url":"https://yoshikitakei.com/"},"record":{"name":"武居由樹オフィシャルサイト","url":"https://yoshikitakei.com/"},"boxrec_id":{"name":"BoxRec IDの手動確認","url":"https://boxrec.com/wiki/index.php/Yoshiki_Takei"},"stance":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/wiki/index.php/Yoshiki_Takei"}}'::jsonb, true
),
(
  'ryosuke-nishida', '西田凌佑', 'にしだ りょうすけ', 'Ryosuke Nishida', NULL, '898844', 'https://boxrec.com/en/box-pro/898844',
  '日本', '1996-08-07', '奈良県香芝市', 'active', '六島ジム', 'スーパーバンタム級', 'サウスポー',
  170, 173, '2019-10-03',
  12, 11, 1, 0, 0, 2,
  true, 'なし', 'IBF世界バンタム級、WBOアジアパシフィック・バンタム級', 'バンタム級',
  NULL, 29, 1, NULL,
  '2026-09-27', 'サム・グッドマン', 'トヨタアリーナ東京', 'Prime Video Boxing 16',
  '3150FIGHT公式プロフィール / Tapology', 'https://www.3150fight.com/profile/143/', '2026-08-20T00:00:00+09:00',
  '{"profile":{"name":"3150FIGHT公式プロフィール","url":"https://www.3150fight.com/profile/143/"},"record":{"name":"Tapology（2026年2月試合後の表示）","url":"https://www.tapology.com/fightcenter/fighters/248265-ryosuke-nishida"},"reach_cm":{"name":"Tapology","url":"https://www.tapology.com/fightcenter/fighters/248265-ryosuke-nishida"},"next_fight_date":{"name":"Amazon公式発表","url":"https://www.aboutamazon.jp/news/entertainment/prime-boxing-16"}}'::jsonb, true
),
(
  'kosei-tanaka', '田中恒成', 'たなか こうせい', 'Kosei Tanaka', NULL, '666339', 'https://boxrec.com/en/box-pro/666339',
  '日本', '1995-06-15', '岐阜県多治見市', 'retired', '畑中ジム', 'スーパーフライ級', 'オーソドックス',
  164, 164, '2013-11-10',
  22, 20, 2, 0, 0, 11,
  true, 'なし', 'WBO世界ミニマム級、WBO世界ライトフライ級、WBO世界フライ級、WBO世界スーパーフライ級', 'ミニマム級、ライトフライ級、フライ級、スーパーフライ級',
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL,
  '北國新聞 / BoxMob', 'https://www.hokkoku.co.jp/articles/-/1765634', '2026-08-20T00:00:00+09:00',
  '{"profile":{"name":"北國新聞","url":"https://www.hokkoku.co.jp/articles/-/1765634"},"record":{"name":"ボクシングモバイル","url":"https://boxmob.jp/sugotoku/boxer/result.html?boxer_id=3919"},"stance":{"name":"TBS公式選手紹介","url":"https://www.tbs.co.jp/sports/boxing/match20201231/players/profile02.html"}}'::jsonb, true
),
(
  'hozumi-hasegawa', '長谷川穂積', 'はせがわ ほづみ', 'Hozumi Hasegawa', NULL, '105935', 'https://boxrec.com/en/box-pro/105935',
  '日本', '1980-12-16', '兵庫県西脇市', 'retired', '真正ボクシングジム', 'スーパーバンタム級', 'サウスポー',
  168, 171, '1999-11-22',
  41, 36, 5, 0, 0, 16,
  true, 'なし', 'WBC世界バンタム級、WBC世界フェザー級、WBC世界スーパーバンタム級', 'バンタム級、フェザー級、スーパーバンタム級',
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL,
  'BoxRec（手動確認） / 西脇市資料', 'https://boxrec.com/en/box-pro/105935', '2026-08-20T00:00:00+09:00',
  '{"profile":{"name":"西脇市資料","url":"https://www.city.nishiwaki.lg.jp/material/files/group/6/201301-14-15.pdf"},"record":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/en/box-pro/105935"},"height_cm":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/en/box-pro/105935"},"reach_cm":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/en/box-pro/105935"},"pro_debut_date":{"name":"BoxRec（手動確認）","url":"https://boxrec.com/en/box-pro/105935"}}'::jsonb, true
)
on conflict (slug) do update set
  name_ja = excluded.name_ja,
  name_kana = excluded.name_kana,
  name_en = excluded.name_en,
  ring_name = excluded.ring_name,
  boxrec_id = excluded.boxrec_id,
  boxrec_url = excluded.boxrec_url,
  nationality = excluded.nationality,
  birth_date = excluded.birth_date,
  birthplace = excluded.birthplace,
  career_status = excluded.career_status,
  gym = excluded.gym,
  weight_class = excluded.weight_class,
  stance = excluded.stance,
  height_cm = excluded.height_cm,
  reach_cm = excluded.reach_cm,
  pro_debut_date = excluded.pro_debut_date,
  total_fights = excluded.total_fights,
  wins = excluded.wins,
  losses = excluded.losses,
  draws = excluded.draws,
  no_contests = excluded.no_contests,
  ko_wins = excluded.ko_wins,
  world_champion_experience = excluded.world_champion_experience,
  current_titles = excluded.current_titles,
  past_major_titles = excluded.past_major_titles,
  world_title_weight_classes = excluded.world_title_weight_classes,
  next_fight_date = excluded.next_fight_date,
  next_opponent = excluded.next_opponent,
  next_venue = excluded.next_venue,
  next_event_name = excluded.next_event_name,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  source_checked_at = excluded.source_checked_at,
  field_sources = excluded.field_sources,
  is_published = excluded.is_published;
